export enum actions {
    GET_INGREDIENTS_REQUEST = "GET_INGREDIENTS_REQUEST",
    GET_INGREDIENTS_SUCCESS = "GET_INGREDIENTS_SUCCESS",
    GET_INGREDIENTS_FAILED = "GET_INGREDIENTS_FAILED",
    CLOSE_MODAL = "CLOSE_MODAL",
    OPEN_MODAL = "OPEN_MODAL",
    OPEN_INGREDIENT_MODAL = "OPEN_INGREDIENT_MODAL",
    OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL",
    SET_INGREDIENT_INFO = "SET_INGREDIENT_INFO",
    SET_ORDER_INFO = "SET_ORDER_INFO",
    CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST",
    CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS",
    CREATE_ORDER_FAILED = "CREATE_ORDER_FAILED",
    ADD_INGREDIENT_ORDER = "ADD_INGREDIENT_ORDER",
    REMOVE_INGREDIENT_ORDER = "REMOVE_INGREDIENT_ORDER",
    ADD_INGREDIENT_BUN_ORDER = "ADD_INGREDIENT_BUN_ORDER",
    SORT_INGREDIENTS = "SORT_INGREDIENTS",
    CLEAR_INGREDIENTS = "CLEAR_INGREDIENTS"
}