export enum wsActions {
        WS_FEED_CONNECTION_START = "WS_FEED_CONNECTION_START",
        WS_FEED_CONNECTION_SUCCESS = "WS_FEED_CONNECTION_SUCCESS",
        WS_FEED_CONNECTION_ERROR = "WS_FEED_CONNECTION_ERROR",
        WS_FEED_CONNECTION_CLOSED = 'WS_FEED_CONNECTION_CLOSED',
        WS_FEED_GET_MESSAGE = "WS_FEED_GET_MESSAGE",
        WS_FEED_SEND_MESSAGE = "WS_FEED_SEND_MESSAGE",

        WS_ORDERS_CONNECTION_START = "WS_ORDERS_CONNECTION_START",
        WS_ORDERS_CONNECTION_SUCCESS = "WS_ORDERS_CONNECTION_SUCCESS",
        WS_ORDERS_CONNECTION_ERROR = "WS_ORDERS_CONNECTION_ERROR",
        WS_ORDERS_CONNECTION_CLOSED = 'WS_ORDERS_CONNECTION_CLOSED',
        WS_ORDERS_GET_MESSAGE = "WS_ORDERS_GET_MESSAGE",
        WS_ORDERS_SEND_MESSAGE = "WS_ORDERS_SEND_MESSAGE"
}
